<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.sift</groupId>
    <artifactId>search-engine</artifactId>
    <version>1.0</version>

    <dependencies>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.23.2</version>
        </dependency>
    </dependencies>
</project>
